### ISSUE TITLE
Unable to get the Google Authentication Access Token?

### ISSUE THREAD

**Issue by ChanakyaSrinivas** [AppWerft/Ti.GoogleSignIn#18]
Hi All,

How to get Google Authentication Access Token for titanium mobile apps (ios and android) ?

**Comment by chmiiller** [comment]
Please check the example folder. There is a JS file in there which you can better understand how to initialize and read the response properties. There is also a video showing how to register your app

**Comment by ChanakyaSrinivas** [comment]
Hi,

As per your suggestion I flowed. Now am able to get access token from response properties.

Actually my requirement is to perform the different operations on google calendar like below

1. Showing list of events
2. Create new event
3. Edit event

Now am trying to show the calendar events based on generated token but am getting below error

**[ERROR] :**  TiHTTPClient: (TiHttpClient-2) [15535,765993] HTTP Error (java.io.IOException): 403 : Forbidden
[ERROR] :  TiHTTPClient: java.io.IOException: 403 : Forbidden
[ERROR] :  TiHTTPClient: 	at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1283)
[ERROR] :  TiHTTPClient: 	at java.lang.Thread.run(Thread.java:818)
[ERROR] :  loadTheEvents HTTP error: [object Object]

**sample code:**

`Google.addEventListener('login', function(e) {
	
	try{
		Ti.API.info(' ***** RESULT: ' + JSON.stringify(e));
		Ti.API.info(' : e.token ' + e.token);
		Ti.API.info(' : e.id ' + e.id);
		Ti.API.info(' : e.idToken ' + e.idToken);
		Ti.API.info(' : e.email ' + e.email);
		Ti.API.info(' : e.givenName ' + e.givenName);
		getAllEvents(e.id , e.token);
	}catch(e1){
		
	}
});

function getAllEvents(calendarId , access_token) {	

	var calenderURL = 'https://www.googleapis.com/calendar/v3/calendars/' + calendarId + '/events?access_token=' + access_token;
	Ti.API.info('calenderURL: ' + calenderURL);
	var xhrList = Ti.Network.createHTTPClient({
		// function called when the response data is available
		onload : function(e) {
			try {
				var eventsResp = JSON.parse(this.responseText);
				Ti.API.info('CPS getAllEvents: ' + eventsResp);
			} catch(e) {

			}
		},
		// function called when an error occurs, including a timeout
		onerror : function(e) {
			Ti.API.error('getAllEvents HTTP error: ' + e);
		},
	});
	xhrList.open("GET", calenderURL);
	xhrList.send();
}`

Can you please help me out how to get the list calendar events based on access token?

**Comment by chmiiller** [comment]
I'm not so sure if I'm able to fix this issue. Does anyone have experience with Calendar?

**Comment by chmiiller** [comment]
Actually, I think the very best is to close this issue and open another one with more details on how to get information from Google Calendar. @ChanakyaSrinivas can you please do this?

**Comment by AppWerft** [comment]
Yes I have.
