### ISSUE TITLE
No login event fired (works in iOS version)

### ISSUE THREAD

**Issue by PietroGranati** [AppWerft/Ti.GoogleSignIn#23]
Hello everyone, I'm tryng to figure out to make module work on Android (SDK 7.0.2 module v3).

I've created the project and the clientID (copied the Web version string) when I clicked on login button the google dialog box appear, I click on my profile, dialog disappear but nothing log in console.

I really don't know what to do now

**Comment by ashishSebu** [comment]
Hi, I'm facing same issue with ios, but this doesn't work when I click on add another user and login with new user, the dialog box disappears and the login event is not triggered.

**Comment by chmiiller** [comment]
Hi @PietroGranati did you manage to make it work?
@ashishSebu I think the problems you're facing are different from what @PietroGranati is saying. If you still have them, can you please open another issue? Thanks!

**Comment by Geryy** [comment]
i have the same problem, in Android (SDK 7.1.0 module v3).

When i clicked on login button and click on my profile nothing log in console. I don't know what is the problem.

**Comment by chhatbargaurang** [comment]
Hello @chmiiller I have a similar problem that [oakleaf](https://github.com/AppWerft/Ti.GoogleSignIn/issues/17) mention but its not signing. I am righting here because this thread is matching with my problem too. I found that my release app working with release certificate key on android, but after launching at playstore it giving error and conflicting with facebook OnActivityResult.

Here are some error I am getting from monitor console.

`07-23 15:03:21.520: E/TiBaseActivity(9398): (main) [0,1663295] Error dispatching onActivityResult event: Attempt to invoke interface method 'boolean com.facebook.CallbackManager.onActivityResult(int, int, android.content.Intent)' on a null object reference`
`07-23 15:03:21.520: E/TiBaseActivity(9398): java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.CallbackManager.onActivityResult(int, int, android.content.Intent)' on a null object reference`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at facebook.ActivityWorkerProxy.onActivityResult(ActivityWorkerProxy.java:74)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at org.appcelerator.titanium.TiLifecycle.fireOnActivityResultEvent(TiLifecycle.java:179)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at org.appcelerator.titanium.TiBaseActivity.onActivityResult(TiBaseActivity.java:810)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at android.app.Activity.dispatchActivityResult(Activity.java:6946)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4173)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at android.os.Handler.dispatchMessage(Handler.java:102)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at android.os.Looper.loop(Looper.java:154)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at android.app.ActivityThread.main(ActivityThread.java:6165)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at java.lang.reflect.Method.invoke(Native Method)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)`
`07-23 15:03:21.520: E/TiBaseActivity(9398): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`
`07-23 15:03:21.521: D/GSignin(9398): (main) [1,1663296] onResult`
`07-23 15:03:21.560: I/GoogleInputMethod(3796): onFinishInput() : Dummy InputConnection bound`
`07-23 15:03:21.560: I/LatinMetricsFactory(3796): Remove content log processors.`
`07-23 15:03:21.591: I/ActivityManager(3170): Killing 10972:com.google.android.apps.maps/u0a117 (adj 906): empty #13`

same apk without publishing isn't have that conflict problem. Its working as expected.
And one more thing that my app having facebook and Google plus login within same Titanium window.
can you guide me over this problem?

**Comment by chmiiller** [comment]
Hi there.
@chhatbargaurang can you try to isolate the problem removing facebook or other modules and see if it still happens?

**Comment by chhatbargaurang** [comment]
@chmiiller Thanks for your response, I found cause of this problem, client using two different account for configuring login and publishing, I got to know about this by taking remote computer to check configuration, after correcting configuration it works. but I still didn't understand why its showing error after published.

**Comment by qasim90** [comment]
I just faced this issue...This was because I created project on http://console.developers.google.com/ Fixed after importing project to Firebase and registering android app with SHA-1 fingerprints in firebase  settings > General tab

**Comment by MotiurRahman** [comment]
Did anyone get any solution? I tested with TI SDK 8.3.1.GA, ti.googlesignin version="3.0.0" and I see "login" event is not firing @PietroGranati @chmiiller but works on iOS.

**Comment by MotiurRahman** [comment]
"login" event seems "clientID" related issue not module.

**Comment by MotiurRahman** [comment]
@chhatbargaurang I am experiencing the same issue during development mode. How did you fix it? Could you please share more details?

**Comment by e3bmo3ty** [comment]
same issue, login event not fired.


any solution ?
